### ISSUE TITLE
Error loading model file not found constants.pkl

### ISSUE THREAD

**Issue by launchd** [DBraun/PyTorchTOP#10]
After loading the plugin in the 'cplusplus_background_matting' TOP, I receive an error loading the model file on that TOP:
`Error: Error loading model: [enforce fail at ..\..\caffe2\serialize\inline_container.cc:222] . file not found: archive/constants.pkl (/project1/cplusplus_background_matting)`

I am using the 'pytorch_mobilenetv2.pth' model, but no matter which model I try this occurs. 
![cpperror2](https://user-images.githubusercontent.com/1222258/103448287-70095600-4c65-11eb-89fa-2261e3af1199.png)

**Comment by DBraun** [comment]
I think you downloaded the wrong file, the ones that have pytorch as a prefix. We want the ones that start with `torchscript_`.

**Comment by launchd** [comment]
The `torchscript_` prefix models also give me the same issue. But it's good to know I should be using those models, thank you.

**Comment by DBraun** [comment]
Can you upload another screenshot? Which model are you using and what are the settings on the C++ TOP? The Bytes per Input model etc.

**Comment by launchd** [comment]
Fixed, I was using the wrong torchscript model files.
