### ISSUE TITLE
OpenCV installation steps not going as planned as ReadMe

### ISSUE THREAD

**Issue by AlejoHarris** [DBraun/PyTorchTOP#4]
When Clicking **Configure**, the pop up window doesn't show the same options as the ReadMe steps.

![image](https://user-images.githubusercontent.com/14794157/103303294-e14ace00-4a05-11eb-9881-42af9dce4efe.png)

**Comment by DBraun** [comment]
Sorry I forgot to explain that pop-up. It's in the README now. Click `Finish` to continue. If you encounter another issue please ask. Thanks.

**Comment by DBraun** [comment]
I updated it one more time (https://github.com/DBraun/PyTorchTOP/commit/4ff0644e9c5975c492a32798056eb8a11e8fa789). It turns out that you don't add `CUDA_TOOLKIT_ROOT_DIR` yourself. If the CUDA stuff is in your system path, then because you enable `WITH_CUDA`, the generate process will generate a project with `CUDA_TOOLKIT_ROOT_DIR` defined.

**Comment by AlejoHarris** [comment]
When building the PyTorchTOP with CMake, this error appears:

> CMake Error at CMakeLists.txt:130 (FIND_PACKAGE):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.
>
>Could not find a package configuration file provided by "OpenCV" with any
  of the following names:
>
>OpenCVConfig.cmake
    opencv-config.cmake
>
>Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

Is the Prefix for OpenCV or LibTorch?

**Comment by DBraun** [comment]
Suppose you built opencv to `C:/opencv/build`. Then you should create a system environment variable for `OpenCV_DIR` equal to `C:/opencv/build`

**Comment by AlejoHarris** [comment]
Now when building the PyTorchTOP appears this error:

![image](https://user-images.githubusercontent.com/14794157/103387570-cc089900-4b04-11eb-9be2-a185273a7f2e.png)

**Comment by DBraun** [comment]
It's possible that you put the `build` directory in the wrong location. Revisit this step: https://github.com/DBraun/PyTorchTOP#building-the-pytorchtop-project

The `build` directory should be a sibling of the `src` and `models` directories.

**Comment by DBraun** [comment]
@AlejoHarris Did you succeed?

**Comment by DBraun** [comment]
Closing due to staleness. Please re-open if issue persists, but don’t try to use higher versions of PyTorch. There’s still a bug with them and so you must use version 1.7.1
