### ISSUE TITLE
No output in TouchDesigner

### ISSUE THREAD

**Issue by launchd** [DBraun/PyTorchTOP#8]
I'm unable to get matting to work in TouchDesigner, despite everything running smoothly. I've checked Touch for errors, added the .dll to plugins, and downloaded the models. I've added the freeze frame to perform the matte as well, but I feel like I'm missing something. 

Is there anything else I should check?
![td](https://user-images.githubusercontent.com/1222258/103440135-2a22a280-4c11-11eb-95cd-22f10bafa8bd.png)

**Comment by DBraun** [comment]
Look for the “Unload plugin” parameter on the C++TOP. I keep that toggle parameter on so that I can make changes to the network before loading the plugin. Toggle it off to load the plugin.

**Comment by launchd** [comment]
Thank you, problem solved!
