### ISSUE TITLE
torchscript_mobilenetv2_fp32.pth

### ISSUE THREAD

**Issue by ryansimrell** [DBraun/PyTorchTOP#9]
After install the cplusplus_background_matting top gives an error saying it is missing this file... "PyTorchTop/models/torchscript_mobilenetv2_fp32.pth" anyone know why that wouldn't generate?

**Comment by DBraun** [comment]
The pretrained torchscript model files can be downloaded from here https://github.com/PeterL1n/BackgroundMattingV2#download. Place them in the models folder. Also be careful to check the Bytes per Model Input custom parameter. It should be 2 for 16-bit models and 4 for 32-bit models.

**Comment by ryansimrell** [comment]
That was it! Thank you so much for getting back to me this is amazing!

**Comment by DBraun** [comment]
Great!
